# Generated by Django 3.0.3 on 2020-04-06 18:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 6, 18, 53, 42, 544739, tzinfo=utc)),
        ),
    ]
